- build.gradle
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
- src/test/resources/application.yml
[CB-20]
🔨 Jira 태스크
[CB-146] 로그인 API 없음
📐 구현한 내용
- CI/CD 중에 발생하는 테스트 실패를 수정하였습니다.
🚧 논의 사항
- 리프레시 토큰 추가
- 테스트 코드 추가
[CB-20]: https://cocobob.atlassian.net/browse/CB-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-146]: https://cocobob.atlassian.net/browse/CB-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cb 146 be 로그인 api가 없음

- src/main/java/com/pinkdumbell/cocobob/config/WebConfig.java
도메인 구매 및 https 적용
[CB-93]
🔨 Jira 태스크
[CB-97]  [BE] https 설정이 필요함
📐 구현한 내용
프론트 엔드
https://petalog.us/ 
백엔드
https://api.petalog.us/
도메인 구매 및 도메인 https 적용
🚧 논의 사항
프론트 엔드에서 사용할 수 있게 cors에 추가하였습니다.
[CB-93]: https://cocobob.atlassian.net/browse/CB-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-97]: https://cocobob.atlassian.net/browse/CB-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CB-97 [feat]: add https address

- src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
어색한 '존재하지 않은 계정입니다.'를 '존재하지 않는 계정입니다.'로 변경
[CB-20]
🔨 Jira 태스크
[CB-185] 어색한 에러메시지 내용 수정
📐 구현한 내용
'존재하지 않은 계정입니다'를 '존재하지 않는 계정입니다'로 변경하였습니다.
🚧 논의 사항
[CB-20]: https://cocobob.atlassian.net/browse/CB-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-185]: https://cocobob.atlassian.net/browse/CB-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CB-185 [refactor]: modify wrong context error message

- src/main/java/com/pinkdumbell/cocobob/config/SwaggerConfig.java
- src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
[CB-252]
🔨 Jira 태스크
[CB-252] [CB-93]
📐 구현한 내용
- Swagger에  Authorization 추가
- 회원가입 정상처리 - > 반려동물 등록 정상처리 : 반려동물 등록 잘못된 message 수정
🚧 논의 사항
Swagger를 통해서 test는 Header에 토큰을 추가할수없어 하지 못하였습니다.
그러나, 이번 수정을 통해서 swgger를 통해서 accessToken을 넣을 수 있게
되면서 swagger를 통해서도 모든 API들을 테스트할 수 있게 하였습니다.
또한, issue에 10년짜리 accessToken을 추가하였으니 해당 토큰을 사용하면은
test용으로 문제 없을 것입니다.
[CB-252]: https://cocobob.atlassian.net/browse/CB-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-252]: https://cocobob.atlassian.net/browse/CB-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-93]: https://cocobob.atlassian.net/browse/CB-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CB-252 [feat]: available Authorization Button

- src/main/java/com/pinkdumbell/cocobob/common/BaseEntity.java
- src/main/java/com/pinkdumbell/cocobob/config/JpaAuditingConfig.java
- src/main/java/com/pinkdumbell/cocobob/domain/common/BaseEntity.java
- src/main/java/com/pinkdumbell/cocobob/domain/daily/Daily.java
- src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
- src/main/resources/db/migration/V5__add_created_updated_at.sql
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserRepositoryTest.java
[CB-151]
🔨 Jira 태스크
[CB-151] BE 엔터티 생성 수정 삭제일자가 없음
📐 구현한 내용
- 엔티티의 생성, 수정시간을 담는 BaseEntity 생성
- JpaAuditingConfig 생성 및 JpaAuditing 활성화
- JpaAuditing 테스트
🚧 논의 사항
[CB-151]: https://cocobob.atlassian.net/browse/CB-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-151]: https://cocobob.atlassian.net/browse/CB-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-151] BE 엔터티 생성 수정 삭제일자가 없음

- src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
- src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/SimplePetInfoDto.java
- src/main/java/com/pinkdumbell/cocobob/domain/pet/image/PetImage.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/UserRepository.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserGetResponseDto.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerUnitTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserRepositoryTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceUnitTest.java
[CB-257]
🔨 Jira 태스크
[CB-257] [BE] 사용자 정보를 가져오는 기능이 필요함
📐 구현한 내용
- GetUserInfo API 작성
- API 작성에 따른 유닛테스트 작성
- 스웨거를 통한 API 명세 작성
- 불필요한 쿼리 제거를 위한 연관관계, 지연로딩 수정
🚧 논의 사항
[CB-257]: https://cocobob.atlassian.net/browse/CB-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-257]: https://cocobob.atlassian.net/browse/CB-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-257] [BE] 사용자 정보를 가져오는 기능이 필요함

- build.gradle
- src/main/java/com/pinkdumbell/cocobob/config/QueryDslConfig.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductPedicate.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductPredicate.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductRepository.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDsl.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDslImpl.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductService.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/dto/FindAllResponseDto.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductDetailResponseDto.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductSimpleResponseDto.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductSpecificSearchDto.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/Like.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeController.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeId.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeRepository.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeService.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/dto/LikeRequestDto.java
- src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
- src/test/java/com/pinkdumbell/cocobob/domain/pet/PetRepositoryTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/product/ProductRepositoryTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/product/ProductServiceTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserRepositoryTest.java
[CB-285] QueryDsl이 적용되지 않음
🔨 Jira 태스크
- [CB-287] 좋아요 기능이 없음
- QueryDSL이 적용되지 않음
📐 구현한 내용
- 좋아요 기능 추가
- 기존 criteria로만 구현할시 join하는 것에 큰 어려움이 있어 좋아요를 표시할 경우 DB 쿼리가 과도하게 발생한다. 그래서 이를 QueryDSL을 사용하여 쿼리수를 적게 사용하였다.
- QueryDSL을 이용하여 상품 목록화시 좋아요수를 확인할 수 있게 하였다.
- QueryDSL을 이용하여 현재 사용자가 좋아요 누른 상품을 볼 수 있게 하였다.
- 상품ID, 가격, 좋아요를 기준으로 상품 목록을 정렬할 수 있도록 하였다.
🚧 논의 사항
- 쿼리 수는 줄었지만 쿼리의 복잡성은 증가
[CB-285]: https://cocobob.atlassian.net/browse/CB-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-287]: https://cocobob.atlassian.net/browse/CB-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cb 285 be query dsl이 적용되지 않음

- .github/workflows/deploy.yaml
- build.gradle
- src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/GoogleOAuthRequest.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/AccountType.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
- src/test/java/com/pinkdumbell/cocobob/CocobobApplicationTests.java
- src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
- src/test/resources/application.yml
[CB-137]
- [CB-299]
🔨 Jira 태스크
[CB-137] [BE] 소셜 로그인 기능이 없음
- [CB-299] 구글 로그인 연동
📐 구현한 내용
- 구글 로그인 구현
- GET /v1/users/google 요청을 보내면 구글 로그인 폼으로 리다이렉트
- 로그인이 완료되면 리다이렉트 URL을 통해 code가 전송됨
- code를 통해 token을 얻어오고 token을 통해 사용자 정보를 얻어와 로그인을 진행함
🚧 논의 사항
- 로그인, 회원가입 코드 리팩토링 필요
- 소셜 로그인 쿼리 스트링을 통해서 한 메서드로 묶을 수 있도록 수정 필요
[CB-137]: https://cocobob.atlassian.net/browse/CB-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-299]: https://cocobob.atlassian.net/browse/CB-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-137]: https://cocobob.atlassian.net/browse/CB-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-299]: …
> [CB-137] [CB-299] [BE] 소셜 로그인 기능이 없음

- src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerUnitTest.java
- src/test/resources/application.yml
[CB-309]
🔨 Jira 태스크
새로 생성된 구글, 카카오 정보를 담는 컴포넌트로 인해 발생하는 테스트 에러 해결
📐 구현한 내용
테스트 에러 해결
🚧 논의 사항
[CB-309]: https://cocobob.atlassian.net/browse/CB-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CB-309 [fix]: add googleOauthInfo & kakaoOauthInfo for test

- src/test/java/com/pinkdumbell/cocobob/CocobobApplicationTests.java
- src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerUnitTest.java
- src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
[CB-137]
- [CB-293]
🔨 Jira 태스크
[CB-137] [BE] 소셜 로그인 기능이 없음
- [CB-293] 애플 로그인 연동
📐 구현한 내용
- 테스트 수정
🚧 논의 사항
[CB-137]: https://cocobob.atlassian.net/browse/CB-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-293]: https://cocobob.atlassian.net/browse/CB-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-137]: https://cocobob.atlassian.net/browse/CB-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-293]: https://cocobob.atlassian.net/browse/CB-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-137] [CB-293] BE 소셜 로그인 기능이 없음 : 테스트 수정

- src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
- src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserGetResponseDto.java
- src/main/resources/db/migration/V8__drop_relation_between_user_with_representativepet.sql
[CB-332]
🔨 Jira 태스크
[CB-332] 사용자 반려동물의 연관관계 때문에 서로 참조하여 삭제할 수 없음
📐 구현한 내용
- 사용자와 대표 반려동물 연관관계(1:1) 삭제
- 사용자 엔티티에서 대표 반려동물 id를 연관관계 없이 가질 수 있도록 수정
- 외래키 제약 수정에 따른 flyway script 작성
🚧 논의 사항
[CB-332]: https://cocobob.atlassian.net/browse/CB-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-332]: https://cocobob.atlassian.net/browse/CB-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-332] [BE] 사용자 반려동물의 연관관계 때문에 서로 참조하여 삭제할 수 없음

- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductService.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeRepository.java
[CB-343]
🔨 Jira 태스크
유저의 찜한 제품을 가져올 수 있다.
📐 구현한 내용
- 유저가 좋아요한 상품들을 조회 가능할 수 있게 하였습니다.
- 해당 API도 페이지네이션 처리 하였습니다.
🚧 논의 사항
- 테스트 코드 작성
[CB-343]: https://cocobob.atlassian.net/browse/CB-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CB-343 [feat]: add browse use wishlist

- src/main/java/com/pinkdumbell/cocobob/config/SwaggerConfig.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeController.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeService.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/like/dto/LikeRequestDto.java
[CB-357]
🔨 Jira 태스크
좋아요 기능시 userId입력을 생략할 수 있도록 함
📐 구현한 내용
토큰을 통해서 user 정보를 파악할 수 있기에 클라이언트에게 추가로 user 정보를 받기 보다는 기존에 개발한 loginuser 어노테이션으로 해결할 수 있게 하였습니다.
또한, LoginUserInfo는 클라이언트에서 입력할 필요 없는 값이기에, swagger에서 표시되는 것을 방지하였습니다.
🚧 논의 사항
[CB-357]: https://cocobob.atlassian.net/browse/CB-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CB357 be 좋아요 기능 사용시 user id 사용 불필요함

- src/main/resources/db/migration/V13__drop_useless_trigger_when_pet_deleted.sql
[CB-369]
🔨 Jira 태스크
[CB-369] [BE] 반려동물 삭제 시 삭제되지 않게 하는 DB 레벨의 트리거 삭제가 필요함
📐 구현한 내용
- flyway script를 통해 반려동물 삭제 시 deleted 값을 update하는 트리거 삭제
- 엔티티의 @SqlDelete 어노테이션을 통해 바뀐 쿼리가 나가서 디비 레벨의 트리거가 필요없다고 판단
🚧 논의 사항
[CB-369]: https://cocobob.atlassian.net/browse/CB-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-369]: https://cocobob.atlassian.net/browse/CB-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-369] fix : 쓸모없는 트리거 삭제

- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductPredicate.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDsl.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDslImpl.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductService.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductKeywordDto.java
- src/main/resources/db/migration/V13__replace_blank_from_proudct_brand.sql
[CB-370]
🔨 Jira 태스크
상품 키워드 제공 API가 없음
📐 구현한 내용
- 상품 키워드 전송시 브랜드명과 상품명에 키워드가 들어가 있는 상품 이름 제공
- 상품 설명 키워드는 제외(업체에 동일한 설명으로 인해 다른 재료명이거나 다른 종류에도 검색되는 경우가 발생)
🚧 논의 사항
- 더욱 유연한 검색 방식 고안
[CB-370]: https://cocobob.atlassian.net/browse/CB-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cb 370 상품 키워드 제공 api가 없음

- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDsl.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDslImpl.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductService.java
- src/main/java/com/pinkdumbell/cocobob/domain/product/dto/RelationProductDto.java
[CB-409]
🔨 Jira 태스크
[CB-404] 연관된 상품을 선별하는 기능 없음
[CB-408] 파이썬 서버가 없음
[CB-409] 스프링 RestAPI를 통해서 연관 상품을 가져올 수 없음
📐 구현한 내용
- Contents Based 방식으로 유사도가 높은 상품 상위 10개 추출(cosine similarity 사용)
- Flask를 통한 파이썬 서버 구축
- 파이썬 서버 CORS 허용
- Dockerfile 작성
- Docker Container를 통해 파이썬 서버 구동
- RestTemplate을 통해서 파이썬 서버로 부터 정보 전달
- 연관 상품 정보 API 개발
- QueryDSL을 통해 연관 상품 정보 Query 작성
🚧 논의 사항
- 연관된 상품 정보를 10개 정도면 충분한지
- 현재는 가장 유사한 상품을 기준으로 가져오는데 다른 기준이 있는지
- 추후에는 CF 적용도 가능할 것으로 보여지는데 어떠한 사용자 데이터를 수집할 수 있을 것인지
[CB-409]: https://cocobob.atlassian.net/browse/CB-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-404]: https://cocobob.atlassian.net/browse/CB-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-408]: …
> Cb 409 be 스프링 rest api를 통해서 연관 상품을 가져올 수 없음

- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDslImpl.java
[CB-418]
[CB-423]
🔨 Jira 태스크
[BE] 상품 조회 데이터 뻥튀기 발생함
📐 구현한 내용
기존에는 좋아요 데이터와 상품을 조인할 필요성이 있었다. 그러나 쿼리의 서브 쿼리가 2개가 들어가게 되면서 join 할 필요가 없어졌다. 또한, 임시 방편으로 distinct를 하였지만, 한 상품의 좋아요 수에 따라서, row수가 엄청 많아지고 중복 처리를 DB가 모두 부담해야하는 문제가 있다. 그렇기에 여러 문제를 유발하는 LEFT JOIN을 제거하여 문제를 해결하였다.
🚧 논의 사항
[CB-418]: https://cocobob.atlassian.net/browse/CB-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-423]: https://cocobob.atlassian.net/browse/CB-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CB-423 [refactor]: remove redundant join table

- src/main/java/com/pinkdumbell/cocobob/domain/record/daily/DailyController.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/daily/DailyResponseClass.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/daily/DailyService.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/daily/dto/DailyCreateResponseDto.java
[CB-429]
🔨 Jira 태스크
- [CB-429] [BE] Daily Note 생성 API 리스폰스에 ID가 필요함
📐 구현한 내용
- 기존 daily 생성 시 null을 반환했는데, 클라이언트 요구에 따라 dailyId 반환
🚧 논의 사항
[CB-429]: https://cocobob.atlassian.net/browse/CB-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-429]: https://cocobob.atlassian.net/browse/CB-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-429] [BE] Daily Note 생성 API 리스폰스에 ID가 필요함

- src/main/java/com/pinkdumbell/cocobob/domain/record/RecordService.java
################
[CB-457]
🔨 Jira 태스크
[CB-457] [BE] 특정 달의 건강 데이터(산책, 데일리, 건강 기록)를 조회할 때 서버 오류가 발생함
이슈 링크 : https://cocobob.atlassian.net/browse/CB-457?atlOrigin=eyJpIjoiZWExMjlkMmM3MjZjNDgzMGFkNzdkZTAxNjEzMmVmZTEiLCJwIjoiaiJ9(문제상황 및 해결방법 포함)
📐 구현한 내용
- 산책 기록을 추가하고 해당 월의 건강 기록들을 조회할 때 발생하는 오류 해결
🚧 논의 사항
[CB-457]: https://cocobob.atlassian.net/browse/CB-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-457]: https://cocobob.atlassian.net/browse/CB-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-457] hotfix : 건강 기록 조회 오류 해결

- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordController.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordRepository.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordResponseClass.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordService.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/RecentWeightsPerDatesDto.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/RecentWeightsResponseDto.java
- src/test/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordRepositoryTest.java
[CB-477]
🔨 Jira 태스크
- [CB-477] BE 최근 7 개의 몸무게 데이터 추이가 필요함
📐 구현한 내용
- 기능 구현에 필요한 컨트롤러 및 DTO 작성
- 서비스, 레포지토리 메서드 구현
- 레포지토리 메서드 테스트
🚧 논의 사항
[CB-477]: https://cocobob.atlassian.net/browse/CB-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-477]: https://cocobob.atlassian.net/browse/CB-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-477] BE 최근 7 개의 몸무게 데이터 추이가 필요함

- src/main/java/com/pinkdumbell/cocobob/common/apilog/ApiLog.java
- src/main/java/com/pinkdumbell/cocobob/common/apilog/ApiLogInterceptor.java
- src/main/java/com/pinkdumbell/cocobob/common/apilog/ApiLogRepository.java
- src/main/java/com/pinkdumbell/cocobob/config/WebConfig.java
- src/main/resources/db/migration/V15__create_api_log.sql
[CB-127]
🔨 Jira 태스크
[CB-127] [BE] 데이터 히스토리 테이블이 없음
📐 구현한 내용
- 인터셉트를 활용하여 API 로그 데이터를 축적할 수 있도록 구현.
- 로그 데이터 테이블 생성
- 인터셉트를 활용해서 API가 호출되면 핸들러에서 처리되기 이전에 로그가 쌓이도록 구현
🚧 논의 사항
[CB-127]: https://cocobob.atlassian.net/browse/CB-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-127]: https://cocobob.atlassian.net/browse/CB-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-127] [BE] 데이터 히스토리 테이블이 없음

- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordController.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordResponseClass.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordService.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/HealthRecordCreateResponseDto.java
[CB-530]
🔨 Jira 태스크
[CB-530] [BE] 식사 기록을 생성할 때 건강 기록이 생성되어 있지 않으면 생성할 수 없음
📐 구현한 내용
- 건강 기록, 식사 기록 생성 시 건강 기록 아이디를 반환할 수 있도록 수정
- 식사 기록 생성 시, 건강 기록 아이디를 받는 것이 아닌, 날짜를 받아서 건강 기록 존재를 확인한 후 findOrCreate 방식으로 건강기록을 생성하고 식사기록 데이터를 추가.
🚧 논의 사항
[CB-530]: https://cocobob.atlassian.net/browse/CB-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-530]: https://cocobob.atlassian.net/browse/CB-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-530] [BE] 식사 기록을 생성할 때 건강 기록이 생성되어 있지 않으면 생성할 수 없음

- src/main/java/com/pinkdumbell/cocobob/domain/product/ProductRepository.java
- src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/HealthRecordDetailResponseDto.java
[CB-539]
🔨 Jira 태스크
- [CB-539] [BE] 건강 기록 급여기록 리스폰스에서 급여 사료의 정보가 부족함
📐 구현한 내용
- 건강 기록 조회 시 식사 기록 내에 등록된 상품이 포함된다 상품 브랜드 상품 사진을 보내주도록 변경
- 캐싱 null key 이슈로 key 값 지정 삭제
🚧 논의 사항
[CB-539]: https://cocobob.atlassian.net/browse/CB-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CB-539]: https://cocobob.atlassian.net/browse/CB-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CB-539] [BE] 건강 기록 급여기록 리스폰스에서 급여 사료의 정보가 부족함
